### ISSUE TITLE
Add default project config and enable CLI configuration

### ISSUE THREAD

**Issue by brech1** [namnc/circom-2-arithc#52]
This issue is related to the **Project Usability** item in the project [overview](https://hackmd.io/@brech1/circom-to-arithc-overview).

To improve usability we need to create our own CLI argument parsing and remove the existent one in the `circom` directory. This one has been built around regular circom usage and needs to be removed, along with any configuration we're not using or planning to.

A project configuration struct has to be made, starting from:

```rust
struct CompilerConfig {
    /// Circuit input file.
    input: String,
    /// Circuit and report output paths.
    output: String,
}
```

This will be helpful when using our project as an executable from a command line interface, but can also serve as inspiration if the project is used as a library.

This will also allow us to update the `clap` dependency.

## Tasks

- [ ] Removal of all code in the `circom` directory related to CLI arguments parsing or project configuration.
- [ ] Implementation of our own CLI, with a `compile` command. 
- [ ] Implementation of a new `CompilerConfig` struct that holds all necessary optional data related to project compilation. Keep in mind this would only be related to the `compile` command on the CLI.
- [ ] Update `clap` dependency.
